### ISSUE TITLE
Error parsing Upload response JSON.  Error was: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by Reality9** [mtesauro/tfCheckmarxUpload#1]
What does this mean?
Error parsing Upload response JSON.  Error was: invalid character '<' looking for beginning of value

file name is number value[appname]-stuff

Can this add the AppID and appName if does not exist in Threadfix?
Need to do a bulk import via this script.

**Comment by mtesauro** [comment]
That error come when the ThreadFix API produces an HTML rather then a JSON response - that can be caused by auth failures or sending an invalid/non-existent App ID into the TF API.  Yes, I've talked to the ThreadFix devs about it - feel free to poke them yourself. ; )

Specifically, that error is coming from line 949 in my tfclient library:
https://github.com/mtesauro/tfclient/blob/master/tfclient.go#L949

when line 172 of checkmarx-uploader.go calls MakeUploadStruct:
https://github.com/mtesauro/tfclient/blob/master/tfclient.go#L949

The MakeUploadStruct call takes the response from the API and tries to convert it from JSON to the UpldResp struct defined at:
https://github.com/mtesauro/tfclient/blob/master/structs.go#L108

All this starts on line 284 of checkmarx-uploader.go:
https://github.com/mtesauro/tfCheckmarxUpload/blob/master/checkmarx-uploader.go#L284

All that said, I'm going to be guessing a bit unless you add the output of the log for tfcheckmarx-uploader - which defaults to ./log/checkmarx-uploader.log.

From what you sent, I'd guess that you have the file names correctly formatted but the App IDs and names in the file name don't already exist in ThreadFix.  Technically speaking, all that is needed is the AppID since the API call I make uses that to link the scan upload to an application in TF.

Auto-adding them is not something I implemented as we used a different method to setup the applications in Checkmarx - a chatbox actually did the setup for us and did the setup of the app in TF if it didn't already exist.  That's something I suppose I could add to this but it may be a bit before I have the bandwidth make that addition.

If you're good at scripting, you could probably write a bash or .bat script to call CURL and setup the apps for you before you run tfCheckmarxUpload on your files- I'm thinking something like:

```
#!/bin/bash

# so things are properly encoded for HTTP, convert space to a plus symbol if the names
# have spaces in them so the Apps: App 1, App two, App3 would look
# like the list below:

APIKEY=PUT-YOUR-API-KEY-VALUE-HERE

for i in 'App+1' 'App+two' 'App3'
do
  DATA="name=$1"
  curl --insecure -H 'Accept: application/json' -X POST --data $DATA https://your.host.com:8443/threadfix/rest/teams/1/applications/new?apiKey=$APIKEY
done

```

The only thing you'd need to do is make sure to get the App ID from the JSON that comes back and ensure the file names have that App ID in them for tfCheckmarxUpload to properly upload them.

Hope that helps.  

Feel free to reply here if you still have questions.

**Comment by dancornell** [comment]
Consider the ThreadFix team poked :)

https://github.com/denimgroup/threadfix/issues/1337

Thanks,

Dan

**Comment by mtesauro** [comment]
Thanks for watching this repo Dan!
